[package]
name = "sequencer"
version = "0.1.0"
edition = "2021"
description = "Merge N feeds ordered by sequence number"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
rand = "0.8.5"
